name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v10
        with:
          skip_adding_nixpkgs_channel: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            ~/.cabal/packages
            dist-newstyle
          key: cabal

      - run: nix-shell --pure --run 'cabal v2-update'
      - run: nix-shell --pure --run 'cabal v2-configure'
      - run: nix-shell --pure --run 'cabal v2-test unit --test-show-details=always --test-option=--color'
